export const LoginLocator = {
    profileIcon: "a[aria-label='Toggle navigation']",
    menuSignInSignUp: ".card-footer",
    tabEmail: ".btn-tab.btn-tab-email.text-center.active",
    tabNoPhone: ".btn-tab.btn-tab-telephone.text-center.active",
    emailInput: "#email",
    nextButton: "button[type='button']",
    passwordInput: "#password",
    loginButton: "#loginButton",
    selectCountry: "#select2-country-container",
    inputPhone: "#telephone",
    buttonGoogle: "button[type='submit']",
    iconSuccessLogin: "img[src='/main/images/login-success.png']",
    successTitle: "#success-title",
    usenameTitle: ".card-title.mb-0",
    profileMenu: "#profile-menu",
    invalidEmailError: ".invalid-feedback.mt-1.d-block",
    invalidPassError: ".invalid-feedback.mt-1.d-block",
} as const;